name: ReSharper

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - master

jobs:
  resharper:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: resharper
        uses: glassechidna/resharper-action@master
        with:
          solution: ${{ secrets.SOLUTION }}
